//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIB.EfTraining
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoItemEntity
    {
        public int Id { get; set; }
        public int Sorting { get; set; }
        public string Description { get; set; }
        public bool IsDefault { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int Version { get; set; }
    }
}
