USE [Training]
GO

/****** Object:  Table [dbo].[BAS_TODOITEM]    Script Date: 4/16/2015 5:01:38 PM ******/
DROP TABLE [dbo].[BAS_TODOITEM]
GO

/****** Object:  Table [dbo].[BAS_TODOITEM]    Script Date: 4/16/2015 5:01:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BAS_TODOITEM](
	[ID] [int] NOT NULL,
	[SORTING] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](50) NULL,
	[ISDEFAULT] [bit] NOT NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[UPDATEDDATE] [datetime] NULL,
	[VERSION] [int] NOT NULL,
 CONSTRAINT [PK_BAS_TODOITEM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


